<?php

namespace Forasoft\ForatestBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query as Query;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends EntityRepository
{

    /* getting answers by question id */
    public function getAnswersByQuestionId($id_question)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT q.description, a.description FROM Forasoft\ForatestBundle\Entity\Question q
        JOIN Forasoft\ForatestBundle\Entity\Answer a WHERE a.idQuestions=q.id AND q.id=:question_id")
            ->setParameter('question_id',$id_question)
            ->getResult(Query::HYDRATE_OBJECT);

        return $query;
    }

}
