<?php

namespace Forasoft\ForatestBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query as Query;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
}