<?php

namespace Forasoft\ForatestBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Forasoft\ForatestBundle\Entity\Test;
use Doctrine\ORM\Query as Query;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends EntityRepository
{

    /* getting the test names */
    public function getTestNames()
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('c.name')
            ->from('ForasoftForatestBundle:Test', 'c', 'c.id')
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

        $ids = array_map('current', $query);

        return $ids;
    }

}
